### PR TITLE
Store Packets and Acknowledgements in Offchain Storage

### LINKED ISSUE #73: Investigate issues using the offchain indexing API in pallet ibc
**Problem definition**

While running integration tests with the relayer, it was noticed that extrinsics that called the offchain api to store packet data offchain were discarded from the transaction pool as Invalid transactions, the same extrinsics were not discarded if their execution did not reach a point where the offchain API was called. 
This needs to be fixed because packet data needs to be stored offchain.

### PR DESCRIPTION
**Pull request by Wizdave97**
closes #73

### CODE REVIEW

**Comment by blasrodri** [comment]
What's the rational for this?

**Comment by Wizdave97** [comment]
We don't want to store packet data on chain, it's just bloat on the runtime storage,  we have the packet commitment on chain already.

**Comment by seunlanlege** [comment]
Yeah i'll come back to this, I just need to merge some fixes to CI first so we can test properly. Because CI is currently using a prebuilt image when it should be building a new one for every PR

**Comment by seunlanlege** [comment]
@Wizdave97 please pull the latest `master` on this branch so we can re-run integration tests

**Comment by seunlanlege** [comment]
@Wizdave97 you'll need to add the flags to the docker-compose file as well

**Comment by Wizdave97** [comment]
> @Wizdave97 you'll need to add the flags to the docker-compose file as well

What flags?

**Comment by Wizdave97** [comment]
> @Wizdave97 you'll need to add the flags to the docker-compose file as well

Ohh, the offchain indexing, on it.

**Comment by Wizdave97** [comment]
> @Wizdave97 please pull the latest `master` on this branch so we can re-run integration tests

Checks are passing now.

**Review by seunlanlege — APPROVED** [review]

**Pull request merged**
